title: Base
author: Finnur Bragason
email: fbragason@outlook.com
description: > # this means to ignore newlines until "aux_links:"
  An Oracle E1 Page Template  

aux_links:
  "Visit on Github":
  - "//github.com/Herdubreid/e1p-base-route"

remote_theme: pmarsceill/just-the-docs
